media:
  input: public/images
  output: /images
content:
  - name: blog
    label: Articulos
    type: collection
    path: 'src/content'
    view:
      fields: [ title, index, pubDate, author, image, category, description ]
    fields:
      - name: description
        label: Descripción
        type: text
      - name: category
        label: Categoría
        type: select
        options:
          multiple: true
          values: ["ECONOMÍA"]
      - name: author
        label: Autor
        type: string
      - name: index
        label: Indexado
        type: boolean
      - name: image
        label: Imagen Principal
        type: image
      - name: pubDate
        label: Fecha
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: juntaDirectiva
    type: collection
    label: Junta Directiva
    path: src/junta
    view:
      fields: [name, title, description, image]
    fields:
      - name: name
        type: string
        label: Nombre
      - name: description
        label: Descripción
        type: text
      - name: image
        type: image
        label: Imagen
      - name: title
        type: string
        label: Titulo
      - name: body
        label: body
        type: rich-text
  - name: revistas
    type: collection
    label: Revistas
    path: src/revistas
    view:
      fields: [link, image]
    fields:
      - name: year
        label: Año
        type: number
      - name: link
        label: Enlace
        type: string
      - name: image
        type: image
        label: Imagen
      - name: body
        label: body
        type: rich-text
      - name: file
        label: PDF
        type: file
  - name: site
    label: Site settings
    path: src/configsite.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)